sudo: required
dist: trusty
language: node_js
node_js:
  - 7
services:
  - docker
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - docker pull mysql:latest
  - docker run -d --network host -e MYSQL_ROOT_PASSWORD=supersecret -e MYSQL_DATABASE=SEED -e MYSQL_USER=SEED -e MYSQL_PASSWORD=SEED mysql:latest
  - docker pull systelab/seed-jee
  - docker run -d --network host -e MYSQL_HOST=127.0.0.1 -e MYSQL_PORT=3306 -e MYSQL_DATABASE=SEED -e MYSQL_USER=SEED -e MYSQL_PASSWORD=SEED systelab/seed-jee:latest
install:
  - npm install
script:
  - npm run e2e
